### ISSUE TITLE
Docker command to build the container fails.

### ISSUE THREAD

**Issue by irwinwilliams** [debelyoo/physio-posenet#28]
When I ran this command, 
**docker build -t physioarkathon/physio-backend:0.1.0 .**
to build the container, I got this error:

ERROR: Could not find a version that satisfies the requirement opencv-python==3.4.5.20 (from -r requirements.txt (line 24)) (from versions: 3.4.8.29, 3.4.9.31, 3.4.9.33, 3.4.10.35, 3.4.10.37, 3.4.11.39, 3.4.11.41, 4.1.2.30, 4.2.0.32, 4.2.0.34, 4.3.0.36, 4.3.0.38, 4.4.0.40, 4.4.0.42)
ERROR: No matching distribution found for opencv-python==3.4.5.20 (from -r requirements.txt (line 24))

**Comment by irwinwilliams** [comment]
It seems to want a version of opencv-python that's not listed here: https://pypi.org/project/opencv-python/#history

**Comment by debelyoo** [comment]
I can't reproduce the problem. When I run `docker build` it does not complain about opencv-python:
`Collecting opencv-python==3.4.5.20 (from -r requirements.txt (line 24))
  Downloading https://files.pythonhosted.org/packages/0a/73/6e8fe7a546678727b0d7f61d952f3421b155374c027403ed79e099b47c3d/opencv_python-3.4.5.20-cp37-cp37m-manylinux1_x86_64.whl (25.4MB)`
